version: '2'
services:
  apache:
    tty: true
    logging:
      driver: syslog
      options:
        syslog-address: "udp://10.10.80.231:514"
        syslog-format: "rfc3164"
        tag: "node-red"
    build:
      context: .
      dockerfile: build/apache/php-7.4/Dockerfile
    image: tschallacka/wintercms-apache:7.4
    ports:
      - "80:80"
      - "9001:9000" # xdebug
    volumes:
      - ./src:/var/www/html
      - ~/.composer/cache:/var/www/.composer/cache
      - ~/.npm:/var/www/.npm
    environment:
      XDEBUG_CONFIG: "remote_host=localhost"
      PHP_IDE_CONFIG: "serverName=Docker"
#      VIRTUAL_HOST: "example.localhost"
    depends_on:
      - db
    links:
      - db
    networks:
      - wintercms-network

  db:
    image: mariadb:10.4.13
    ports:
     - 3300:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wintercms
      - MYSQL_USER=wintercms
      - MYSQL_PASSWORD=wintercms
    volumes:
      - dbdata:/var/lib/mysql
      - ./backups:/var/tmp/backups
    networks:
      - wintercms-network

  redis:
    image: redis
    ports:
     - 6379
    networks:
      - wintercms-network
      
networks:
  wintercms-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
